api_platform:
    title: my_project
    version: 1.0.0

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Enum'
