framework:
    cache:
        prefix_seed: my_project_cache
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

        pools:
            cache.rate_limiter:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_DSN)%'

when@test:
    framework:
        cache:
            app: cache.adapter.filesystem
            default_redis_provider: null
            pools:
                cache.rate_limiter:
                    adapter: cache.adapter.filesystem
                    provider: null
