mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(DEFAULT_URI)%/.well-known/mercure'
            jwt:
                secret: '%env(MERCURE_PUBLISHER_JWT_SECRET)%'
                publish: '*'
