security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        docs:
            pattern: ^/api/(docs|forgotten_password_requests|_health)
            security: false  # @TODO: Find a way to protect the docs in prod

        login_refresh:
            pattern: ^/api/login_refresh
            stateless: true
            provider: user_provider
            user_checker: Oxodao\QneOAuthBundle\Security\OAuthUserChecker
            refresh_jwt:
                check_path: /api/login_refresh

        login:
            pattern: ^/api/login
            stateless: true
            provider: user_provider
            user_checker: Oxodao\QneOAuthBundle\Security\OAuthUserChecker
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern: ^/api
            lazy: true
            stateless: true
            jwt: ~

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/api/_health, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/forgotten_password_requests, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
