framework:
    default_locale: en
    set_locale_from_accept_language: true
    enabled_locales: ['en', 'fr']

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
