name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/app/Dockerfile
          target: frankenphp_prod
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            MY_PROJECT_VERSION=${{ github.ref_name }}
            MY_PROJECT_COMMIT=${{ github.sha }}
          cache-from: type=gha,scope=release-image
          cache-to: type=gha,scope=release-image,mode=max
